[Front] JS Code Convention 통일
TEAM-MAT/gomin-sageori pull request #34
Opened 2022-06-24 03:01 UTC by unbroken2650

[Front] JS Code Convention 통일

2022-06-26 14:53 UTC, makemyway-kr approved these changes

2022-06-26 14:53 UTC, makemyway-kr commented on gomin-sageori_front/src/SetUpProxy.js
> +      target: "http://localhost:8080", //express server add
express server가 아니니까 주석 지워주면 좋을듯. 잘못된 정보니까

2022-06-26 14:53 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/main/Intro.js
> +  const introBackStyle = css`
styled 많이 쓰던데 한번 찾아봐서 그거 써보면 좋지 않을까?

2022-06-26 14:55 UTC, unbroken2650 commented on gomin-sageori_front/src/UI/main/Intro.js
> +  const introBackStyle = css`
styled보다 낫다고 해서 emotion 썼던거야
[노션](https://www.notion.so/Front-e7ddadd18c9e44eda61c8f1f3861a71e#c0a647f3179042ef8b7b5d69870dd6dd)

2022-06-26 14:55 UTC, unbroken2650 commented on gomin-sageori_front/src/SetUpProxy.js
> +      target: "http://localhost:8080", //express server add
@intersoom

2022-06-26 15:02 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/main/Intro.js
> +  const introBackStyle = css`
ㅇㅎ ㅇㅋ 귯

2022-06-26 15:02 UTC, makemyway-kr commented on gomin-sageori_front/src/SetUpProxy.js
> +      target: "http://localhost:8080", //express server add
그냥 Spring Server라고 하던지 아니면 API서버로..?

2022-06-26 15:13 UTC, makemyway-kr commented on gomin-sageori_front/src/SetUpProxy.js
>  module.exports = (app) => {
다른 파일들 보면 ES6 문법으로 하고 있는것 같은데 module.exports는 es6 아니지 않어?

2022-06-26 15:15 UTC, makemyway-kr approved these changes

2022-06-27 09:43 UTC, makemyway-kr requested changes
setupProxy.js 파일에 common.js 방식으로 되어있는거 es6로 변경만 하면 될듯

2022-06-28 05:49 UTC, intersoom commented on gomin-sageori_front/src/SetUpProxy.js
>  module.exports = (app) => {
export로 수정했어요

2022-06-28 05:49 UTC, intersoom commented on gomin-sageori_front/src/SetUpProxy.js
> +      target: "http://localhost:8080", //express server add
삭제 했습니당~

2022-06-28 07:12 UTC, makemyway-kr approved these changes

2022-06-28 07:12 UTC, makemyway-kr commented on gomin-sageori_front/src/SetUpProxy.js
> +export default SetUpProxy;
굿!

2022-06-28 07:12 UTC, merged