Favorites api
TEAM-MAT/gomin-sageori pull request #48
Opened 2022-07-17 12:41 UTC by sangcheol12

즐겨찾기 추가, 삭제, 조회, 수정
추가 : 멤버ID와 추가할 레스토랑ID 리스트를 보내기
삭제 : 멤버ID와 삭제할 레스토랑ID 리스트를 보내기
수정 : 멤버ID와 추가할 레스토랑ID 리스트, 삭제할 ID 리스트를 보내기
조회 : api/member/favorites/{멤버ID}

2022-07-17 12:47 UTC, makemyway-kr requested changes

2022-07-17 12:47 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +import java.util.*;
util.*으로 하지말고 구체적으로 쓰는것만 import해주세요. 오버헤드 늘어나용

2022-07-17 12:47 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +    @PostMapping("/favorites/add")
URL에는 동사(verb)를 적지 않습니다. 오직 접근하는 리소스만 적어놓아야되고 행위는 method로 구분하는거에요
저번에 설명했던것같은뎅

2022-07-17 12:47 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +    @PutMapping("/favorites/modify")
이것도 마찬가지로 행위 X 그냥 /favorites만

2022-07-17 12:47 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +    @DeleteMapping("/favorites/delete")
이것도

2022-07-17 12:51 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +            , notes = "MemberId와 제거할 favorites 배열을 통해 즐겨찾기 삭제 (URL : api/member/favorites/delete)",
특정 식당만을 즐겨찾기에서 제거하는거는 update로 하는게 맞는 것 같고, delete는 전체 즐겨찾기를 삭제할 때만 하는게 맞는듯.

2022-07-17 12:53 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/repository/JpaMemberRepository.java
> +        member.setFavorites(oldFavories);
부분적으로만 지우는 것 같은데, 전체 삭제로 바꿔야할듯. 부분 삭제는 update로.

2022-07-17 12:53 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/service/MemberService.java
> +import java.util.*;
여기도 util.* 말고 필요한것만 import하는걸로

2022-07-17 12:54 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/service/RestaurantService.java
> +    public Set<Restaurant> findSpecificDataById(List<Long> selectedIds) throws Exception {
이건 모죠?????

2022-07-17 12:54 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/service/RestaurantService.java
> +    public Set<Restaurant> findSpecificDataById(List<Long> selectedIds) throws Exception {
기존에 있던 메소드랑 뭐가다른거야?

2022-07-17 12:54 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/transfer/AddDeleteFavoritesParam.java
> +@Setter
request parameter는 다른거 내가 작성한거 참고해서 swagger용 설명 달아줘

2022-07-17 12:55 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/transfer/FavoritesParam.java
> +public class FavoritesParam {
결과를 리턴해주는거면 favoritesReturnParam뭐 이렇게 용도까지 적어주는게 알기 좋을듯!

2022-07-17 12:56 UTC, sangcheol12 commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/service/RestaurantService.java
> +    public Set<Restaurant> findSpecificDataById(List<Long> selectedIds) throws Exception {
이건 리스트로 넘어온 식당들만 ID 값으로 디비에서 가져오는 함수에요

2022-07-17 12:57 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/service/RestaurantService.java
> +    public Set<Restaurant> findSpecificDataById(List<Long> selectedIds) throws Exception {
그냥 기존에 있던걸 여러번 사용하면 안되는거얍? 만약에 리스트를 커버할 목적이라면 함수 이름이 알아보기 어려운것같아

2022-07-17 13:05 UTC, sangcheol12 commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/service/RestaurantService.java
> +    public Set<Restaurant> findSpecificDataById(List<Long> selectedIds) throws Exception {
기존에 있는건 ID로 한개만 가져오거나 DB에 있는 모든 데이터를 가져오는건데 이건 List로 들어온 ID에 해당하는 restaurant만 가져오는거야 함수 이름을 좀 더 직관적으로 바꿔볼게

2022-07-17 13:15 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/service/RestaurantService.java
> +    public Set<Restaurant> findSpecificDataById(List<Long> selectedIds) throws Exception {
엉 그려 이름을 좀 바꾸자

2022-07-17 14:45 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +    @GetMapping("favorites/{id}")
{id}/favorites이래야할듯!

2022-07-18 10:17 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +            favoritesParam.setUserfavorites(restaurantList);
전체 식당 정보를 보내주기보다는 id와 이름, 네이버지도 주소만 보내줘도 될거같은데 (기획에 따라 다르겠지만)

2022-07-18 10:24 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/transfer/FavoritesAddParam.java
> +    public Long getMemberId() {
유저 PK말고 userId로 받는게 맞는것같아

2022-07-18 10:29 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +    @DeleteMapping("/{id}/favorites")
이것도 userid로

2022-07-18 10:36 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +            favoritesParam.setUserfavorites(restaurantList);
여쯤에서 오류나는거아닐까 싶은데

2022-07-18 10:37 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/controller/MemberController.java
> +    @GetMapping("/{id}/favorites")
URL에서 id를 받는게 아니라 userId를 받아서 처리하도록!

2022-07-18 10:38 UTC, makemyway-kr requested changes

2022-07-18 10:38 UTC, makemyway-kr commented on gomin-sageori_Server/src/main/java/MAT/gominsageori/transfer/FavoritesModifyParam.java
> +        return memberId;
이것도 userId로~

2022-07-19 12:27 UTC, makemyway-kr approved these changes
굿! 수고했어용

2022-07-19 12:27 UTC, merged