리팩토링(I)
TEAM-MAT/gomin-sageori pull request #51
Opened 2022-08-01 11:03 UTC by unbroken2650

- Main.js 에서 ‘질문+버튼들’ 을 하나의 컴포넌트로 분리
- 대표 메뉴 사이즈 조절
- S3 이미지 반영 + 사진 크기 조절
- 모바일) 버튼 밖에 터치해도 눌리는 오류
- ESLint, Prettier 적

2022-08-01 11:45 UTC, makemyway-kr commented on gomin-sageori_front/src/SetUpProxy.js
> +      target: process.env.REACT_APP_EC2_URL,
오 env파일 굿굿!

2022-08-01 11:45 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/main/Menu.js
> +import * as MenuIcon from '@emotion-icons/boxicons-regular';
잘 몰라서 그런데 import MenuIcon from '파일이름' 이랑 뭐가 다른거에영?

2022-08-01 11:45 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/reusable/BasicButton.js
> +    <div className="BasicButton" key={shortId}>
혹시 shortId는 어떤 의미인가용?

2022-08-01 11:49 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/reusable/RecommendList.js
> +  }, []);
제가 알기로 useEffect에 []를 주면 mount 될 때 함수가 실행되는 걸로 알고있는데, store값이 안바뀌어서 기존에 선택했던게 계속 나오는건지 우선 그 리액트 개발자도구? 로 한번 확인해보셨나용? 왜 그렇게 된건지 저도 궁금해성

2022-08-03 03:42 UTC, unbroken2650 commented on gomin-sageori_front/src/UI/main/Menu.js
> +import * as MenuIcon from '@emotion-icons/boxicons-regular';
eslint 맞추다가 바꿨을 걸 의미 없어

2022-08-03 03:44 UTC, unbroken2650 commented on gomin-sageori_front/src/UI/reusable/BasicButton.js
> +    <div className="BasicButton" key={shortId}>
6번째 줄 보면 패키지인데 key에 랜덤값 넣어주는거

2022-08-03 03:45 UTC, unbroken2650 commented on gomin-sageori_front/src/UI/reusable/RecommendList.js
> +  }, []);
시간이 지나면 바뀌는데 그게 속도가 늦었었어. 20개로 바꾸고 난 다음에 테스트 해보고 바꿔야 할듯

2022-08-03 08:48 UTC, intersoom commented on gomin-sageori_front/src/UI/reusable/RecommendList.js
> +  const checkTime = (start, end) => {
이런 함수들 utils로 빼면 좋을 것 같아요 로직 <-> 컴포넌트 분리가 필요할듯

2022-08-03 08:48 UTC, intersoom commented on gomin-sageori_front/src/pages/Recommend.js
> +                  <RecommendList key={shortId} id={key.id} name={key.name} />
근데 그 key error 계속 뜨던데 해결됐나용..?

2022-08-03 09:05 UTC, unbroken2650 commented on gomin-sageori_front/src/pages/Recommend.js
> +                  <RecommendList key={shortId} id={key.id} name={key.name} />
이거 말고 메인 쪽인 거 같던데 나중에 보려고

2022-08-03 09:05 UTC, unbroken2650 commented on gomin-sageori_front/src/UI/reusable/RecommendList.js
> +  const checkTime = (start, end) => {
오케이

2022-08-03 11:24 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/reusable/BasicButton.js
> +    <div className="BasicButton" key={shortId}>
ㅇㅎ 굿

2022-08-03 11:25 UTC, makemyway-kr requested changes
수민이가 올린 수정사항 반영한 뒤 Approve -> merge하면될듯!

2022-08-04 13:32 UTC, makemyway-kr approved these changes
확인

2022-08-07 10:07 UTC, makemyway-kr requested changes
![image](https://user-images.githubusercontent.com/58161987/183285824-3f16c6c4-855a-488e-88d3-74be04300376.png)
![image](https://user-images.githubusercontent.com/58161987/183285861-b1ae8ed9-3e2e-4aa6-aa31-d0c979a33e6e.png)
사진 오류와 slice? method관련 오류가 발생했어요

2022-08-07 10:07 UTC, makemyway-kr commented
![image](https://user-images.githubusercontent.com/58161987/183285887-30c35e09-1cf3-4442-a62d-657437b8f559.png)

key관련 오류도 출력되네요

2022-08-07 10:08 UTC, makemyway-kr commented
![image](https://user-images.githubusercontent.com/58161987/183285911-195cd647-1bc7-4c22-866c-51bf56811f04.png)

2022-08-07 10:09 UTC, unbroken2650 commented
> ![image](https://user-images.githubusercontent.com/58161987/183285824-3f16c6c4-855a-488e-88d3-74be04300376.png)
> 
> ![image](https://user-images.githubusercontent.com/58161987/183285861-b1ae8ed9-3e2e-4aa6-aa31-d0c979a33e6e.png)
> 
> 사진 오류와 slice? method관련 오류가 발생했어요

대체 이미지 아직 안 했다고 노션에 써있습니다

2022-08-07 10:17 UTC, makemyway-kr approved these changes
대체 이미지만 얼른 해주시면 되겠네요~ Approve합니당 👍

2022-08-07 10:53 UTC, merged