리팩토링
TEAM-MAT/gomin-sageori pull request #52
Opened 2022-08-01 15:04 UTC by intersoom

- Recommed.js와 BestRecommend.js에서 state 형태를 obj 형태로 수정함
- 찾아보기 버튼 색상(#f5ad79) 수정
- Selection.js: 선택한 키워드(userSelection)를 localStorage 이용해서 값을 넘겨서 표시
-> prefer가 Set 형태로 localStorage에 안 담겨서 arr 형태로 따로 코드 빼서 작성
`localStorage.setItem('preferSelection', JSON.stringify(preferSelectionArr));
localStorage.setItem('userSelection', JSON.stringify(userSelection));`
-> 영어로 넘어오는 값을 preferFilter 함수 이용해서 한글로 바꿔줌
`function preferFilter(value) {
    const preferSelectionFiltered = [...preferSelection];
    value.map((elm, idx) => (
      preferSelectionFiltered.splice(idx, 1, preferArr[preferArr.indexOf(elm) - 1])
    ));
    return preferSelectionFiltered;
  }`

2022-08-02 13:03 UTC, makemyway-kr commented on gomin-sageori_front/src/SetUpProxy.js
> +      target: 'http://3.39.97.45',
이거 수호가 한거랑 합쳐줘 .env파일로 수호가 했어
ip주소 노출하면 보안에 안좋아

2022-08-02 13:03 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/recommend/Selection.js
> +          preferFilter(preferSelection).map((elm, index) => (
elm은 뭐의 약자인가용? @intersoom @unbroken2650

2022-08-02 13:06 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/recommend/Selection.js
> +  const prevSelection = JSON.parse(localStorage.getItem('userSelection'));
제가 알기로 localStorage는 unMount해도 남아있는걸로 아는데 unmount시에 초기화시키거나 삭제하는 메소드가 있어야 하지 않을까요?

2022-08-02 13:08 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/recommend/Selection.js
> +      preferSelectionFiltered.splice(idx, 1, preferArr[preferArr.indexOf(elm) - 1])
제 생각에는 Arr이 아니라 딕셔너리 형태로 만들어서 그거로 한영 변환을 하면 더 쉬울 것 같아요

2022-08-02 13:12 UTC, makemyway-kr requested changes

2022-08-02 13:12 UTC, makemyway-kr commented on gomin-sageori_front/src/state/store.js
>      prefer: new Set(),
이건 궁금해서 물어보는건뎅 set이 안돼서 Arr로 바꿨다 했는데 여기서는 Set()으로 선언해주는데 왜 그런건가용?

2022-08-02 18:30 UTC, intersoom commented on gomin-sageori_front/src/UI/recommend/Selection.js
> +          preferFilter(preferSelection).map((elm, index) => (
element용

2022-08-02 18:31 UTC, intersoom commented on gomin-sageori_front/src/UI/recommend/Selection.js
> +  const prevSelection = JSON.parse(localStorage.getItem('userSelection'));
넵 초기화해야할 것 같네요 반영하겠습니다!

2022-08-02 18:31 UTC, intersoom commented on gomin-sageori_front/src/UI/recommend/Selection.js
> +      preferSelectionFiltered.splice(idx, 1, preferArr[preferArr.indexOf(elm) - 1])
그게 더 깔끔할 것 같긴하네요! 반영하겠습니다.

2022-08-02 18:32 UTC, intersoom commented on gomin-sageori_front/src/state/store.js
>      prefer: new Set(),
Set()으로 초기화하는거는 userSelection 파트고 arr로 바꾼 부분은 localStorage로 넘겨주는 값이에요

2022-08-03 03:50 UTC, unbroken2650 commented on gomin-sageori_front/src/state/store.js
>      prefer: new Set(),
Set으로 쓰는 건 Array로 하려다가 같은 특성을 2번 누르면 Array에 있는 지 확인하는 과정이 필요해서 Set으로 썼는데, localStorage에 안 들어가니까 변환해준거야.

2022-08-03 03:51 UTC, unbroken2650 commented
전 위에 올라온 코멘트들 빼고 리뷰 마쳤습니다👍🏼

2022-08-03 08:49 UTC, intersoom commented on gomin-sageori_front/src/SetUpProxy.js
> +      target: 'http://3.39.97.45',
넵

2022-08-03 11:23 UTC, makemyway-kr commented on gomin-sageori_front/src/state/store.js
>      prefer: new Set(),
ㅇㅎ 오케잉~

2022-08-05 14:02 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/recommend/Selection.js
> +      localStorage.removeItem('preferSelection');
굿! 확인!

2022-08-05 17:03 UTC, unbroken2650 approved these changes

2022-08-06 15:54 UTC, intersoom commented
피드백 모두 반영 완료해뒀습니다. 다만, 지금 recommend 페이지에서 정보 불러오는 과정에서 발생하는 문제는 해결 못한 상태입니당!

2022-08-07 07:15 UTC, closed without merging