메뉴바 제작
TEAM-MAT/gomin-sageori pull request #58
Opened 2022-08-18 20:29 UTC by intersoom

- notFound 페이지 추가
- GO-SA 글씨 클릭시, 홈 페이지로 돌아가게 설정
- 메뉴아이콘을 header 컴포넌트로 빼서 메뉴바 따라서 안 움직이게 설정
ㄴ props로 state 넘겨줌
- z-index 사용해서 메뉴바가 젤 위로 오게끔 만들어줌

2022-08-18 20:31 UTC, intersoom commented
메뉴바에 들어가는 내용들 중 음식점 찾기 빼고는 공모전에서는 필요 없는 것들이라서 어떻게 할지 의견 주세용! 
<현재 메뉴바 내용>
- 음식점 찾기
- 방문했던 음식점
- 즐겨찾기
- 마이페이지

2022-08-19 06:28 UTC, unbroken2650 commented
https://github.com/TEAM-MAT/gomin-sageori/blob/b38f5e1b70daefc87cce11c3cbef11e134c64a70/gomin-sageori_front/src/UI/reusable/RecommendList.js#L37
console문 지워주세요!

2022-08-19 06:33 UTC, unbroken2650 commented on gomin-sageori_front/src/pages/NotFound.js
> +      Page Not Found
홈 화면으로 돌아가기를 넣으면 어떨까요?

2022-08-19 06:34 UTC, unbroken2650 commented
나머진 좋아요! 이상 없는듯

2022-08-19 13:11 UTC, makemyway-kr commented
> 메뉴바에 들어가는 내용들 중 음식점 찾기 빼고는 공모전에서는 필요 없는 것들이라서 어떻게 할지 의견 주세용!
> 
> <현재 메뉴바 내용>
> 
> * 음식점 찾기
> * 방문했던 음식점
> * 즐겨찾기
> * 마이페이지

@intersoom  밑의 세개는 회색 disable처리 해놓고 밑에 추후 오픈 예정 적어놓으면 어떨까욥? 오히려 공모전에서는 안좋게 작용하려나 cc @unbroken2650 @sangcheol12 의견좀 주세요

2022-08-19 13:17 UTC, makemyway-kr requested changes
위의 것 외에는 딱히 없네요~ 굿

2022-08-19 13:17 UTC, makemyway-kr commented on gomin-sageori_front/src/pages/Main.js
> +  const regionArr = [
이것도 전에 한-영 같이 dict로 하면 훨신 코드 가독성(직관적)이나 유지보수에 편할듯!

2022-08-19 13:18 UTC, unbroken2650 commented
> 메뉴바에 들어가는 내용들 중 음식점 찾기 빼고는 공모전에서는 필요 없는 것들이라서 어떻게 할지 의견 주세용!
> 
> <현재 메뉴바 내용>
> 
> * 음식점 찾기
> * 방문했던 음식점
> * 즐겨찾기
> * 마이페이지

전 없애는 게 좋을 것 같아요 공모전에서 어떻게 심사할 지 모르겠지만 @makemyway-kr 말처럼 안 좋게 작용할 수도

2022-08-21 10:45 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/main/Menu.js
> +    <div css={props.handleMenu ? selectedMenuStyle : menuStyle} id="Menu">
handleMenu prop이 정확히 어떤 변수인가영?

2022-08-22 12:21 UTC, intersoom commented on gomin-sageori_front/src/UI/main/Menu.js
> +    <div css={props.handleMenu ? selectedMenuStyle : menuStyle} id="Menu">
햄버거 버튼이 클릭되었는지 안되었는지 Header.js에서 state 값을 props로 넘겨주는 것입니당!

2022-08-22 12:34 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/main/Menu.js
> +    <div css={props.handleMenu ? selectedMenuStyle : menuStyle} id="Menu">
그러면  isHambergerClicked 이게 좀 더 깔끔하지 않을까용?

2022-08-22 12:34 UTC, makemyway-kr reviewed
굿

2022-08-22 15:51 UTC, makemyway-kr approved these changes
굿!

2022-08-22 15:55 UTC, merged