식당 0개 출력 페이지
TEAM-MAT/gomin-sageori pull request #59
Opened 2022-08-20 15:34 UTC by unbroken2650

> **[#58 ](https://github.com/TEAM-MAT/gomin-sageori/pull/58)이 포함된 PR입니다. 먼저 merge 후 이 PR을 확인해주세요.**

[동작 영상](https://i.imgur.com/wT6NQGd.mp4)

주요 내용 : 
'찾아보기' 선택 시 로딩 화면 3초 후
1) 추천 결과가 있다면 -> 식당 표시
2) 없다면 -> '결과 없음' 페이지 표시

2022-08-21 10:38 UTC, makemyway-kr reviewed
https://anerim.tistory.com/221
이것처럼 axios로 fetch해오는 메소드를 시작하기 전에 로딩 state를 true로 놓고 완료되면 false로 바꿔서 보여주는 컴포넌트를 바꾸면 어떨까 싶어

2022-08-21 10:40 UTC, makemyway-kr commented on gomin-sageori_front/src/pages/Recommend.js
> +  const [recommendBool, setRecommendBool] = useState(false);
recommendBool보다는 isRecommended 이런 형태로 뜻을 알아보기 좋게 하는게 어떨까요?

2022-08-21 10:40 UTC, makemyway-kr requested changes
1차 코멘트 끝

2022-08-21 10:43 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/recommend/NoResult.js
> +      {loading ? (
no Result 컴포넌트가 따로 나와있고 밑에 Recommend 코드를 봐서는 이미 api호출을 완료한 뒤에 로딩 화면을 띄우는 것 같은데 혹시 맞을까요? 내가 본게 맞다면 이렇게 하는 방식은 별로 좋지 않은듯해서

2022-08-21 11:17 UTC, unbroken2650 commented on gomin-sageori_front/src/pages/Recommend.js
> +  const [recommendBool, setRecommendBool] = useState(false);
> 

이거 나도 봤는데 zustand에서 recommendResult가 전역 상태처럼 쓰여서 로딩 상태까지 그렇게 하려면 너무 대공사라서 놔뒀어.. ㅋㅋ 해볼까?

2022-08-21 11:18 UTC, makemyway-kr commented on gomin-sageori_front/src/pages/Recommend.js
> +  const [recommendBool, setRecommendBool] = useState(false);
3초라는 시간도 꽤 길기도하고 어설프게 될까봐 뭔가... 시간 되면 고쳐보자

2022-08-21 11:18 UTC, makemyway-kr commented on gomin-sageori_front/src/pages/Recommend.js
> +  const [recommendBool, setRecommendBool] = useState(false);
JIRA에 올려줭~

2022-08-21 11:19 UTC, unbroken2650 commented on gomin-sageori_front/src/UI/recommend/NoResult.js
> +      {loading ? (
> https://anerim.tistory.com/221 이것처럼 axios로 fetch해오는 메소드를 시작하기 전에 로딩 state를 true로 놓고 완료되면 false로 바꿔서 보여주는 컴포넌트를 바꾸면 어떨까 싶어

이거 나도 봤는데 zustand에서 recommendResult가 전역 상태처럼 쓰여서 로딩 상태까지 그렇게 하려면 너무 대공사라서 놔뒀어.. ㅋㅋ 해볼까?

2022-08-21 11:19 UTC, unbroken2650 commented on gomin-sageori_front/src/UI/recommend/NoResult.js
> +      {loading ? (
> no Result 컴포넌트가 따로 나와있고 밑에 Recommend 코드를 봐서는 이미 api호출을 완료한 뒤에 로딩 화면을 띄우는 것 같은데 혹시 맞을까요? 내가 본게 맞다면 이렇게 하는 방식은 별로 좋지 않은듯해서

그러려나 고쳐보지뭐

2022-08-21 11:21 UTC, makemyway-kr commented on gomin-sageori_front/src/UI/recommend/NoResult.js
> +      {loading ? (
일단 JIRA에 올려두고 다른 시급한것들 먼저 처리해보자

2022-08-22 06:18 UTC, makemyway-kr reviewed
https://ko.reactjs.org/docs/concurrent-mode-patterns.html
usetransition 이거 한번 봐볼랭?

2022-08-22 11:41 UTC, makemyway-kr approved these changes
굿~

2022-08-22 12:35 UTC, merged